/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: 'var(--ink)',
        'ink-soft': 'var(--ink-soft)',
        'ink-faint': 'var(--ink-faint)',
        paper: 'var(--paper)',
        surface: 'var(--surface)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        cipher: 'var(--cipher)',
        'cipher-soft': 'var(--cipher-soft)',
        qubit: 'var(--qubit)',
        'qubit-soft': 'var(--qubit-soft)',
        'risk-critical': 'var(--risk-critical)',
        'risk-critical-bg': 'var(--risk-critical-bg)',
        'risk-high': 'var(--risk-high)',
        'risk-high-bg': 'var(--risk-high-bg)',
        'risk-medium': 'var(--risk-medium)',
        'risk-medium-bg': 'var(--risk-medium-bg)',
        'risk-low': 'var(--risk-low)',
        'risk-low-bg': 'var(--risk-low-bg)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '24px',
        '6': '32px',
        '7': '48px',
        '8': '64px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
      },
      fontSize: {
        display: ['40px', { lineHeight: '1.12', letterSpacing: '-0.01em', fontWeight: '600' }],
        h1: ['26px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        h2: ['19px', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['15px', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        small: ['12.5px', { lineHeight: '1.5', fontWeight: '400' }],
        mono: ['13px', { lineHeight: '1.5', fontFamily: "'IBM Plex Mono', monospace" }],
      },
    },
  },
  plugins: [],
};
